nameOverride: front-end

image:
  repository: docker.io/bluebrown/statics
  pullPolicy: Always
  tag: 0.1.0

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: "*.elb.eu-central-1.amazonaws.com"
      paths:
        - path: /statics(/|$)(.*)
          pathType: Prefix

probes:
  startup:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    failureThreshold: 30
    periodSeconds: 10
  liveness:
    httpGet:
      path: /
      port: http
    periodSeconds: 30
    failureThreshold: 1
