#!/bin/bash

set -euo pipefail

cd terraform/kubernetes/components
terraform destroy -auto-approve || true
cd -

cd terraform/kubernetes/cluster
terraform destroy -auto-approve || true
cd -

cd terraform/classic
terraform destroy -auto-approve || true
cd -

jq -r '.builds[].artifact_id|split(":")[1]' packer/packer-manifest.json |
  xargs -I {} aws ec2 deregister-image --image-id {}

aws ec2 describe-snapshots --owner self --filters Name=tag:Example,Values=true --output json |
  jq -r '.Snapshots[].SnapshotId' |
  xargs -I {} aws ec2 delete-snapshot --snapshot-id {}
